apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: c2lkZGlrdmFkbGE3ODY=
    mongo-root-password: REhSVVZB  # you can use any property name not only mongo-root-password

